"""
💻 code_executor.py — Safe Python Code Executor
=================================================
Executes Python code generated by the Quant agent.
Used for Monte Carlo simulations and financial calculations.
Runs in a restricted namespace for safety.
"""

import io
import sys
import traceback


def execute_python_code(code: str) -> dict:
    """
    Execute a Python code string safely and capture its output.

    Args:
        code: Python code to execute

    Returns:
        dict with keys:
            - success (bool): Whether execution succeeded
            - output (str): Printed output from the code
            - variables (dict): Variables defined in the code's namespace
            - error (str): Error message if failed
    """
    # Restricted namespace — only allow safe libraries
    safe_globals = {
        "__builtins__": __builtins__,
    }

    # Allow importing only approved libraries
    allowed_imports = {
        "numpy", "np", "math", "random", "statistics",
        "json", "collections", "itertools", "functools",
    }

    # Capture stdout
    old_stdout = sys.stdout
    captured_output = io.StringIO()
    sys.stdout = captured_output

    result = {
        "success": False,
        "output": "",
        "variables": {},
        "error": "",
    }

    try:
        exec(code, safe_globals)
        result["success"] = True
        result["output"] = captured_output.getvalue()

        # Extract user-defined variables (skip builtins and modules)
        for key, val in safe_globals.items():
            if key.startswith("_"):
                continue
            if isinstance(val, (int, float, str, bool, list, dict, tuple)):
                result["variables"][key] = val

    except Exception as e:
        result["error"] = f"{type(e).__name__}: {e}\n{traceback.format_exc()}"

    finally:
        sys.stdout = old_stdout

    return result


def extract_numeric_results(exec_result: dict) -> dict:
    """
    Pull out the key numeric results from executed code.
    Looks for standard variable names the Quant agent should produce.

    Args:
        exec_result: Result from execute_python_code()

    Returns:
        Dict with financial metrics found in the code output
    """
    variables = exec_result.get("variables", {})

    # Standard names the Quant agent is instructed to produce
    expected_keys = [
        "success_probability",
        "roi",
        "break_even_months",
        "break_even_units",
        "expected_revenue",
        "expected_costs",
        "net_profit",
        "risk_score",
        "mean_profit",
        "median_profit",
        "worst_case",
        "best_case",
        "std_deviation",
    ]

    results = {}
    for key in expected_keys:
        if key in variables:
            results[key] = variables[key]

    # Also check output for any printed results
    output = exec_result.get("output", "")
    if output:
        results["_raw_output"] = output

    return results


if __name__ == "__main__":
    test_code = """
import numpy as np
import random

# Simple Monte Carlo test
n_simulations = 1000
profits = []
for _ in range(n_simulations):
    revenue = random.gauss(100000, 20000)
    costs = random.gauss(70000, 15000)
    profit = revenue - costs
    profits.append(profit)

success_probability = sum(1 for p in profits if p > 0) / n_simulations
mean_profit = np.mean(profits)
median_profit = np.median(profits)
worst_case = np.percentile(profits, 5)
best_case = np.percentile(profits, 95)
std_deviation = np.std(profits)
roi = (mean_profit / 70000) * 100

print(f"Success Probability: {success_probability:.2%}")
print(f"Mean Profit: ${mean_profit:,.0f}")
print(f"ROI: {roi:.1f}%")
"""
    print("Testing code executor...\n")
    result = execute_python_code(test_code)
    print(f"Success: {result['success']}")
    print(f"Output:\n{result['output']}")
    print(f"\nNumeric results: {extract_numeric_results(result)}")
